### ISSUE TITLE
Clear graph button

### ISSUE THREAD

**Issue by jovelleu** [copton/eeg-mindflex#12]
Sometimes one has done a few measurements and just wants to have a clean new start. 

A button to clear all signals from the screen and to start plotting a new graph (without disconnecting or cleaning the averaged signal array) would be nice.

**Comment by copton** [comment]
@jovelleu  should the button only reset the EEG graph or also the raw data plot?

**Comment by jovelleu** [comment]
It's sufficient to reset the eeg graph only

Alexander Bernauer ***@***.***> schrieb am Sa., 14. Dez.
2024, 22:27:
